version: "3.9"

services:
  funflow_postgres:
    image: postgres:16
    container_name: funflow_postgres
    volumes:
      - ~/.pg/pg_data/funflow:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - 5432:5432

  funflow_project:
    build: 
      context: .  # Контекст указывает на текущую директорию с Dockerfile
    container_name: funflow_django
    depends_on:
      - funflow_postgres
    volumes:
      - static_volume:/funflow/static
      - media_volume:/funflow/media
    env_file:
      - .env
    command: >
      bash -c "./manage.py collectstatic --noinput && ./manage.py migrate && ./manage.py runserver 0.0.0.0:8000"
    ports:
      - "9000:8000"

volumes:
  static_volume:
  media_volume: